source: site
baseurl: ""
title: keedrop
url: "https://keedrop.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
host: 0.0.0.0

languages: ["en", "de", "ru"]
exclude_from_localizations: ["assets", "humans.txt", "robots.txt", "sitemap_index.xml"]

# Build settings
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

include:
  - humans.txt

jekyll_tidy:
  exclude: ["humans.txt", "*.js"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
