name: Build

env:
  KEEDROP_CONTACT_GPGKEY: "0xdeadbead"
  KEEDROP_CONTACT_EMAIL: thedude@dudism.church
  KEEDROP_CONTACT_ADDRESS: Hollywood
  KEEDROP_CONTACT_NAME: Jeffrey Lebowski
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go

    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true
      id: ruby

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Ruby dependencies
      run: |
        sudo apt-get install libpq-dev
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run E2E tests
      uses: cypress-io/github-action@v6
      with:
        start: bundle exec rake serve

    - name: Get Go dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build server
      run: go build -v .

    - name: Test server
      run: go test -v .
